python: can't open file '3': [Errno 2] No such file or directory
